version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-chatbot_db}
      POSTGRES_USER: ${POSTGRES_USER:-chatbot_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-chatbot_user}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile-fixed
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-chatbot_user}:${POSTGRES_PASSWORD:-secure_password}@postgres:5432/${POSTGRES_DB:-chatbot_db}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      FLASK_ENV: production
      SECRET_KEY: ${SECRET_KEY:-fallback_secret_key}
    ports:
      - "5000:5000"
    volumes:
      - app_uploads:/app/uploads
      - app_faiss:/app/faiss_index
      - app_logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  app_uploads:
  app_faiss:
  app_logs: